---
title: "AD4S: Adaptive Design for Software"
output:
  blogdown::html_page:
    toc: false
    toc_depth: 1
    fig_width: 8
    dev: "svg"
author: "Houston Haynes"
date: '2021-04-11T15:59:43+05:30'
featuredpath: img
featured: adaptivedesign.png
ogfeatured: H3_og_wide_adaptivedesign.png
emblem: perspective.png
description: Making the Case to Bring Broader Systems Thinking to Software Based Systems
draft: false
tags:
- Accessibility
- a11y
- Design
- Domain Driven Design
- DDD
categories: 
- Perspective
weight: 1
editor_options: 
  chunk_output_type: inline
---
# TL;DR

I have created "Adaptive Design for Software" [AD4S] as a culmination of my decades of experience building hardware and software technologies. The intent is to move beyond coding opinions and usher discussion to broader design considerations. The goal of AD4S is to provide fertile ground for teams to consider how to avoid costly engineering, security, operations and legal/regulatory risks - as well as other harms - that emerge from the current fashion of "move fast and break things". The result will be an honest contract between business leaders and engineering teams in recognizing the true cost and actual consequences for their product decisions. I have reserved a handful of useful TLDs [adaptivedesign.software, ad4s.org, ad4s.net, etc.] and will be considering several options for creating non-profit and open-source resources to partner with like-minded companies and individuals. 

# Everything Old Is New Again

## Lessons from 'The Two Bobs'

## Moving Beyond Agile Software

## DDD and higher-order software design

## Are Regulated Systems All That Different?

# Software Engineering as a Practice

## Risk Calculation

### Finance

### Automotive

### Telecom

### Global Manufacturing

### Healthcare

# Avoiding the Slippery Slopes

## No Analysis Paralysis

## It's not a framework

## It's not a shortcut

## Checklists are for experts

# Privacy

# Security
