---
title: "AD4s - Best Practices is Fool's Gold"
output:
  blogdown::html_page:
    toc: false
    toc_depth: 1
    fig_width: 8
    dev: "svg"
author: "Houston Haynes"
date: '2021-04-11T15:59:43+05:30'
featuredpath: img
featured: adaptivedesign.png
ogfeatured: h3_og_wide_adaptivedesign.png
emblem: perspective.png
description: Moving Beyond Agile SDLCs Using Systems Thinking and Adaptive Management
draft: true
tags:
- AD4S
- Observability
- Accessibility
- a11y
- o11y
- Domain Driven Design
- DDD
- ethics
- AI
- ML
- CNCF
- Distributed Systems
- Cloud
categories: 
- Perspective
weight: 101
editor_options: 
  chunk_output_type: inline
---

`r blogdown::shortcode("alert-perspective", "info", "Working Draft(s):", "This entry is one among several. Instead of an extended read [I use the metaphor of Martin Luther's 95 Theses] I have opted to publish them here as a loose collection of ideas and am saving the finer points for the proposed formalized site. Stay tuned!")`

# Making Sound Decisions while Maintaining Momentum

## Limit the expense of revisiting complex decisions

## Rigor cannot be proceduralized

## Every Company has its own Domain Specific Language

### Mapping business lexicon to design entities

## Reducing the Barriers to Entry

## Complexity: Essential vs Accidental vs Incidental

# CAP Theorem

## Choosing On a Gradient - the Brewer exception

"Choosing any two" between consistency, availability and partition tolerance is *not* an real choice, but it's a rhetorical device to remind software engineers that those choices lurk at every level in a solution. By extension, architectural patterns make those choices of how those factors are weighed and balanced against each other. And even where the architect is not *intentionally* looking at those factors, technology decisions reveal implied balancing of how they view the CAP theorem in the context of system under their purview. Recognizing the various shades/gradients and triangulating between them is key to a resilient architecture.

## Redistributing Risk

## Managing Modes of Failure

## Making the Instrumentation Easier to Change

## Fault and Resource Isolation

# Best Practices vs Good Practice - a GxP approach

### The Lessons Are Everywhere

### Artifacts: Work vs Design vs Status

### Natural Tensions in Systems Design

### Realize the Power of Outlining Known Unknowns

### Avoiding conflicting & loaded terms (buzzword bingo)

## Fragile Software - Inexperience is the Worst Teacher

### Beyond Agile Development

### Saying 'yes' to consistency, 'no' to dogma

<div id="reactiveisnotenough"/>

## Being Reactive is not enough

The `r blogdown::shortcode("url-link", "reactive manifesto", "https://www.reactivemanifesto.org/")` makes progress over agile patterns and practices but still suffers from a form navel-gazing. Its self-concern imbues an unhealthy projection onto a systems users which in-effect is an abdication of responsibility. It naively creates a tautological loop where it only responds to directed input - and fails to take any notice of larger contextual boundaries in which the system *should* (and in certain legal contexts, must) operate. This includes governance and compliance, privacy, ethics, accessibility, inclusion and sustainability. It rather naively assumes that there will be no contention between competing interests of users (and system managers) and therefore makes no attempt to be the arbiter of where and how certain compromises are to be made. It also assumes that there's no potential avenues for misuse or abuse, which as we're all well aware is a very dangerous assumption. What if the business managers or marketing team asks the engineers to change the system to behave in a way that's illegal? It has this tacit assumpton if constituencies don't specifically *ask* for these things to be considered - and therefore expresses no interest in addressing those broader systemic concerns.

A system has to be smarter than "there could be rakes is in the yard" only for the handle to smack the users/engineers/legal team in the face at every step.
`r blogdown::shortcode("youtube", "aRq1Ksh-32g")`
<br>
And the world of large systems software is full of examples of exactly that happening time and again.

## Case Studies in Unforced Errors

`r blogdown::shortcode("header-centered", "3", "Case Study: Discord")`

`r blogdown::shortcode("tweet", "1382018677026000897")`

`r blogdown::shortcode("header-centered", "3", "Case Study: WhatsApp")`

`r blogdown::shortcode("tweet", "1382452553233797120")`

`r blogdown::shortcode("header-centered", "3", "Case Study: Slack")`

`r blogdown::shortcode("tweet", "1375030200745000960")`

## DDD and higher-order software design

## Are Regulated Systems All That Different From Commercial systems?

# Regarding Software Design as a Practice

## Evaluate Software Design as a peer to Other Disciplines
Software is the digital infrastructure of our lives. When you're in a vehicle going over a bridge, you want the engineers who built it to be more qualified than "some socially mal-adapted guy who dropped out of Harvard".

#### legal, medical, construction & civil engineering

<p>&nbsp;</p>

### GDPR, CCPA and related standards and regulations

`r blogdown::shortcode("ext-flink-card", "https://fortune.com/2021/04/02/aclu-shares-data-facebook-third-parties-digital-privacy")` 

# The "So what" Factor

## Is this an internal or external-facing process - both?

## Similarities to SOC 2 & 3

## Cost/Benefits Analysis

# Avoiding the Slippery Slopes

## No Analysis Paralysis

## It's not a framework

## It's not a shortcut

## Checklists are for experts

## Privacy

## Security

`r blogdown::shortcode("ext-link-card", "https://traced.app/2021/04/13/whatsapp-status-loophole-is-aiding-cyberstalkers")`
<p>&nbsp;</p>

## Ethics and Algorithmic Accountability

`r blogdown::shortcode("tweet", "1382426863008681986")`
<p>&nbsp;</p>

# What Led Me To This Point

### Lessons from 'The Two Bobs'

### Further Lessons from regulated verticals

#### Finance

#### Automotive

#### Telecom

#### Global Manufacturing

#### Healthcare

`r blogdown::shortcode("ext-flink-card", "https://www.imt.ie/news/health-researchers-blocked-by-gdpr-12-04-2021")`
<p>&nbsp;</p>

## Risk Calculation - a CVE-inspired model

Not every problem requires a software engineering "fix". Aside from the up-front costs, those over-engineered solutions can sometimes open up side doors to other problems that quickly spin out into their own engineering quagmires. Sometimes it's more cost/time effective to put a remediation procedure in place and document it as part of the solution. That's why a 'risk' type in solution management is key to surfacing that shared responsibility across engineering, operations, legal and other business groups.

[Embed/integrate doc from 2009] https://int.h3tech.dev/pdf/HHaynes_2009_simpleCVE_model_for_issue_mgmt.pdf

## Earned & Inherent Limitations of Agile Software Development

# Meta-process: Designing AD4S

## Managing the conversation

## B2C versus B2B considerations

## Commercial versus Enterprise Systems

## Build vs Buy Considerations

## Managing Growth and Adaptation

## Slippery Slopes

## Cautionary Tales

# In closing

## Further Reading

`r blogdown::shortcode("ext-flink-card", "https://abbycovert.com/make-sense/")`
<p>&nbsp;</p>

`r blogdown::shortcode("ext-flink-card", "https://www.infoq.com/articles/C4-architecture-model/")`
<p>&nbsp;</p>

`r blogdown::shortcode("ext-flink-card", "https://structurizr.com/")`
<p>&nbsp;</p>




Geez - have you really read this far?