---
title: "Adaptive Design for Software - A Proposal"
output:
  blogdown::html_page:
    toc: false
    toc_depth: 1
    fig_width: 8
    dev: "svg"
author: "Houston Haynes"
date: '2021-04-11T15:59:43+05:30'
featuredpath: img
featured: adaptivedesign.png
ogfeatured: H3_og_wide_adaptivedesign.png
emblem: perspective.png
description: Moving Beyond Agile SDLCs Using Systems Thinking and Adaptive Management
draft: true
tags:
- Accessibility
- a11y
- Design
- Domain Driven Design
- DDD
categories: 
- Perspective
weight: 1
editor_options: 
  chunk_output_type: inline
---
# TL;DR

Adaptive Design for Software [AD4S] started as a thought experiment - a moment of clarity from my 20+ years in software and managing teams - from start-ups to multi-national conglomerates. AD4S is a rubric for evaluating decisions in complex software while maintaining a first-create-then-evaluate working pattern. It provides **de**scriptive and **pre**scriptive guidance for teams to evaluate for and avoid costly mistakes in user experience, performance, scale, accessibility, sustainability, security as well as mitigate legal and regulatory risks. It also provides a declarative framework for anticipating potential *unintended harms* and related ethical considerations - particularly those ripple effects that constantly surface in "move fast and break things" culture.

The intent of AD4S is to establish the shared responsibilities among the various constituencies that build, maintain and use the software. Think of it as version management for higher-order product guidance. Through curation of an **AD4S ledger** a shared agreement is established between the company and its customers as well as other affected groups, and provides a guide rails to the engineering teams that support those systems they build and maintain. 

AD4S aspires to make measurable the **true cost** and actual consequences of product engineering decisions. In order to make it useful to as many organizations as possible it is conceived as a community-led project, which will pose many challenges and opportunities. For that purpose a handful of useful TLDs have been reserved. [adaptivedesign.software, ad4s.org, ad4s.net, etc.] The next step is to establish the proper location for contributions to be collected and receive comments from the broader community. The result will be a clearinghouse of information where concepts and course-corrections can be mapped out. The hope and expectation is that organizations and individual contributors of good faith will help cultivate AD4S precepts and help build an actionable, responsive and responsibility-minded compendium for crafting better software.

<h2 style="text-align:center;">-- Outline --</h2>

# Everything Old Is New Again
There are natural innovation and implementation cycles in software architecture. It's been that way since the 1970s. With the proliferation of commoditized compute and storage, patterns once thought untenable are now seeing renewed interest. But there's a dark side to progress. Due to the "surface area" of digital technologies the threats to data security have grown exponentially. Many of the intentionally naive patterns from earlier eras existed in an inherently bounded context - of limited access and confined compute space (a system used and maintained at a specific location with limited or no internet access) As those early architectural ideas are re-imagined for the information age, so too must shielding and resiliency be re-imagined for those patterns to be useful in a forward-looking digital landscape.

`r blogdown::shortcode("ext-link-card", "https://www.scmagazine.com/home/security-news/vulnerabilities/namewreck-is-the-latest-collision-between-tcp-ip-and-the-standards-process")` 

## Good design and proper engineering is everyone's business

## Limit the expense of revisiting complex decisions

## Every Company has its own Domain Specific Language

### Mapping business lexicon to design entities

## Reducing the Barriers to Entry

## Complexity: Essential vs Accidental vs Incidental

## Redistributing Risk

### Managing Modes of Failure

## Making the Instrumentation Easier to Change

### The Lessons Are Everywhere

### Artifacts: Work vs Design vs Status

# Best Practices vs Good Practice - a GxP approach

### Natural Tensions in Systems Design

### Realize the Power of Outlining Known Unknowns

### Avoiding conflicting & loaded terms (buzzword bingo)

## Fragile Software - Inexperience is the Worst Teacher

### Beyond Agile Development

### Saying 'yes' to consistency, 'no' to dogma

## Avoiding unforced errors

`r blogdown::shortcode("header-centered", "3", "Case Study: Discord")`

`r blogdown::shortcode("tweet", "1382018677026000897")`
<p>&nbsp;</p>

`r blogdown::shortcode("header-centered", "3", "Case Study: WhatsApp")`

`r blogdown::shortcode("tweet", "1382452553233797120")`
<p>&nbsp;</p>

`r blogdown::shortcode("header-centered", "3", "Case Study: Slack")`

`r blogdown::shortcode("tweet", "1375030200745000960")`
<p>&nbsp;</p>

## DDD and higher-order software design

## Are Regulated Systems All That Different From Commercial systems?

# Regarding Software Design as a Practice

## Evaluate Software Design as a peer to Other Disciplines
Software is the digital infrastructure of our lives. When you're in a vehicle going over a bridge, you want the engineers who built it to be more qualified than "some socially mal-adapted guy who dropped out of Harvard".

#### legal, medical, construction & civil engineering

<p>&nbsp;</p>

### GDPR, CCPA and related standards and regulations

`r blogdown::shortcode("ext-link-card", "https://fortune.com/2021/04/02/aclu-shares-data-facebook-third-parties-digital-privacy")` 
<p>&nbsp;</p>

# The "So what" Factor

## Is this an internal or external-facing process - both?

## Similarities to SOC 2 & 3

## Cost/Benefits Analysis

# Avoiding the Slippery Slopes

## No Analysis Paralysis

## It's not a framework

## It's not a shortcut

## Checklists are for experts

## Privacy

## Security

`r blogdown::shortcode("ext-link-card", "https://traced.app/2021/04/13/whatsapp-status-loophole-is-aiding-cyberstalkers")`
<p>&nbsp;</p>

## Ethics and Algorithmic Accountability

`r blogdown::shortcode("tweet", "1382426863008681986")`
<p>&nbsp;</p>

# What Led Me To This Point

### Lessons from 'The Two Bobs'

### Further Lessons from regulated verticals

#### Finance

#### Automotive

#### Telecom

#### Global Manufacturing

#### Healthcare

`r blogdown::shortcode("ext-link-card", "https://www.imt.ie/news/health-researchers-blocked-by-gdpr-12-04-2021")`
<p>&nbsp;</p>

## Risk Calculation - a CVE-inspired model

Not every problem requires a software engineering "fix". Aside from the up-front costs, those over-engineered solutions can sometimes open up side doors to other problems that quickly spin out into their own engineering quagmires. Sometimes it's more cost/time effective to put a remediation procedure in place and document it as part of the solution. That's why a 'risk' type in solution management is key to surfacing that shared responsibility across engineering, operations, legal and other business groups.

[Embed/integrate doc from 2009] https://int.h3tech.dev/pdf/HHaynes_2009_simpleCVE_model_for_issue_mgmt.pdf

## Earned & Inherent Limitations of Agile Software Development

# Meta-process: Designing AD4S

## Managing the conversation

## B2C versus B2B considerations

## Commercial versus Enterprise Systems

## Build vs Buy Considerations

## Managing Growth and Adaptation

## Slippery Slopes

## Cautionary Tales

# In closing

## Further Reading

`r blogdown::shortcode("ext-link-card", "https://abbycovert.com/make-sense/")`
<p>&nbsp;</p>

`r blogdown::shortcode("ext-link-card", "https://www.infoq.com/articles/C4-architecture-model/")`
<p>&nbsp;</p>

`r blogdown::shortcode("ext-link-card", "https://structurizr.com/")`
<p>&nbsp;</p>




Geez - have you really read this far?