---
title: "Highlighting (the Good, the Bad, and the Unencoded)"
output:
  blogdown::html_page:
    toc: false
    toc_depth: 1
    fig_width: 8
    dev: "svg"
author: "Houston Haynes"
date: '2020-07-24T11:59:43+05:30'
featuredpath: img
featured: highlightjs.png
ogfeatured: H3_og_wide_highlightjs.png
emblem: responsive.png
cover: \img\contact_image_large.png
description: An approach to dynamic code markup in HighlightJS with Fira Code ligatures for extra flair
draft: false
tags:
- Rmarkdown
- blogdown
- Hugo
- JavaScript
- Fira Code
- HighlightJS
categories: 
- Sidebar
weight: 
editor_options: 
  chunk_output_type: inline
---

# Flexing with Flexibility

This site shows examples of my work in a variety of domains. Not only does "full stack engineering" require ventures into territories far and wide, my career has also migrated through several language *families* over the years. And as you see on this site I still return to them on occasion. So along with *insert "SQL + Data Science language of choice" here* the ability to display an array of formats is more than a nice-to-have. I started with `r blogdown::shortcode("url-link", "HighlightJS,", "https://highlightjs.org/")` "out of the box" as it is part of the Hugo template I selected, but it still required some tweaks to encode HTML and related formats. 

## Stage One: Encoding on the Fly

It all started with wanting to have it *both* ways - meaning I wanted to be able to view/edit the code snippet in the editor *and* I wanted the markup to show up correctly on the page. A bit of research online revealed this gem in JavaScript:

<figure><figcaption class="caption">Encodes special characters within a code block</figcaption>
`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-firstJS.png")`
</figure>
This gave me the benefit of clarity during edit. Not every code block "lights up" in the editor like the sample below, but the formatting and general layout is preserved. If you've ever tried to edit encoded markup inline you know what a mess it can become if you miss just one encoding character. 
<figure><figcaption class="caption">VSCode screen grab of HTML from Serverless Contact Page Sidebar</figcaption>
`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-unencodedHTML.png")`
</figure>
It wouldn't be impossible to maintain that portion of the page "encoded" if it was the only one. But imagine a code-snippet-heavy site with those little "land mines" sprinkled throughout. Things become brittle, and issues become time consuming even when the change seems innocuous. So this approach gave some latitude in seeing code blocks in a form that's very close to how they'd appear on the page, which makes maintenance more approachable.

## Stage Two: Little Bugs Everywhere

But as usual, there was a catch. Once a "quick fix" was in place it rippled out to adversely affect and other snippets. Honestly, I didn't spot the issue as a *code issue* until I brought in `r blogdown::shortcode("url-link", "Fira Code,", "https://github.com/tonsky/FiraCode")` to express ligatures. 

<div class="row">
<div class="col-md-6">
<figure><figcaption class="caption">This R snippet...</figcaption>
<pre><code class="r">hc <- highchart() |></code></pre>
</figure>
</div>
<div class="col-md-6">
<figure><figcaption class="caption">...looked like this.</figcaption>
<pre><code class="html">hc &lt;- highchart() %&gt;%</code></pre>
</figure>
</div>
<div class="col-md-6">
<figure><figcaption class="caption">And that SQL snippet ...</figcaption>
<pre><code class="sql">... + datetime >= to_date ...</code></pre>
</figure>
</div>
<div class="col-md-6">
<figure><figcaption class="caption">...looked like that.</figcaption>
<pre><code class="html">... + datetime &gt;= to_date...</code></pre>
</figure>
</div>
</div>

This wrinkle robbed Fira Code of its ability to make a nice, concise impression. At first I thought I had pasted in poorly marked-up code. But then I looked deeper to realize the inserted blocks were fine. After some head-scratching I checked the JavaScript doing the inline-encoding, and it began to dawn on me that it was "too broad" for what I needed.

`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-otherJS.png")`
In the version above I set exclusions for the code classes that I *didn't* want encoded. The "not" indicator seemed to do the trick, until I kept running into more and more exceptions. At that point there were more "not" clauses than actual code that required encoding. So I flipped the script and simply declared which classes I *wanted* to encode.

`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-lastJS.png")`

This is both more logical and more maintainable. I only need to add a class to that list in the declaration if and when I have another language that requires markup. As a side note, I'll say that I *don't* use Django, but here it's used to highlight the Hugo shortcodes, which use double-braces in the HTML. I spotted that VSCode auto-detected those files as Django - so I used that as a cheat code to highlight the double-braced parameters.

<figure><figcaption class="caption">Final version of JavaScript - formatted as JavaScript</figcaption>
<pre><code class="javascript">document.querySelectorAll("code.html, code.xml, code.django").forEach(function(element) {
    element.innerHTML = element.innerHTML.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
});</code></pre>
</figure>

HighlightJS is pretty great, but it does struggle with certain things. That's why I used screen shots of the JavaScript code along with the embed, which tries to encode escaped characters. It just goes to show that even highly-regarded, long-lived OS projects like HighlightJS are also works in progress. But between the screen grabs and the embedded block above, anyone looking to lift this for their site should be able to piece it together.

## Stage Three: Exceptions to the Rules
So after that excursion I still found that certain things were not displaying correctly. It's not that it looked *bad* per se, but it wasn't the detailed code block that I wanted to show. If you look at the first image below, you'll see that you can get the general idea of the HTML that's returned by the JavaScript snippet. But like the rest of the code showcased on this site, specifics matter. So I made a compromise and simply hand-encoded the HTML blocks and pasted them into the JS to "just make it work" for this case.

<div class="row">
<div class="col-md-4">
<figure><figcaption class="caption">JavaScript with inline HTML</figcaption>
`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-inlineHTML.png")`
</figure>
</div>
<div class="col-md-4">
<figure><figcaption class="caption">Encoded HTML placed inline</figcaption>
`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-encodedHTML.png")`
</figure>
</div>
<div class="col-md-4">
<figure><figcaption class="caption">Final view of corrected markup</figcaption>
`r blogdown::shortcode("fancybox-dark-theme-ok", "/img", "HighlightJS-HTMLinJS.png")`
</figure>
</div>
</div>
I can live with these small segments of encoded HTML inline within the sample. And honestly, I wouldn't even know where to begin to make a programmatic solution work in this mixed case. Since the pieces of code are relatively small, and (so far) it's the only one like this on my site, I'm pretty happy to let it go at that. But the bigger win here is the ability to work more quickly in dropping in code snippets un-doctored and continue working. That not only lets me focus on "the fun part" of doing the actual work, but it also relieves some of the friction in considering *which* code samples I might present because of something being un-friendly when displayed in a code block. Now, pretty much everything is fair game.
